### ISSUE TITLE
非管理员怎么使用

### ISSUE THREAD

**Issue by QiangF** [dupontjoy/RimeIME-Portable#1]
运行批处理需要管理员权限怎么解决啊？
谢谢！

**Comment by dupontjoy** [comment]
一般右键都有以管理员权限运行这个菜单的

**Comment by QiangF** [comment]
可是我没有管理员权限，难道不能以普通用户运行吗？

**Comment by dupontjoy** [comment]
@QiangF 改了一下批处理, 将"管理员权限运行"內置到批处理了, 应该直接双击运行就好. 如果还不行, 那我也没办法啦
