### ISSUE TITLE
倉頡週刊確実已経創立了

### ISSUE THREAD

**Issue by ejsoon** [dupontjoy/RimeIME-Portable#3]
地址在[這裏](http://blog.ejsoon.win/cjzone)
本刊的建立，旨在講述倉頡規則的正確理解，以及**制止一些人用不對的理論誤導群衆。** 
同時也會講述倉頡輸入法的故事與發展。各位如果有興趣，歡迎投稿。

![cjzone1](https://user-images.githubusercontent.com/17146567/97845909-2dd89c80-1d28-11eb-8b5d-ce0ca0bf133b.png)

**Comment by ejsoon** [comment]
![cjzone1](https://user-images.githubusercontent.com/15373838/97850401-f02b4200-1d2e-11eb-9ec7-c75d25a7640b.png)

**Comment by dupontjoy** [comment]
tm有病是吧
关了还发

**Comment by ejsoon** [comment]
地址在[這裏](http://blog.ejsoon.win/cjzone)
本刊的建立，旨在講述倉頡規則的正確理解，以及**制止一些人用不對的理論誤導群衆。** 
同時也會講述倉頡輸入法的故事與發展。各位如果有興趣，歡迎投稿。

![cjzone1](https://user-images.githubusercontent.com/17146567/97845909-2dd89c80-1d28-11eb-8b5d-ce0ca0bf133b.png)

**Comment by ejsoon** [comment]
> tm有病是吧
> 关了还发
我開的時候，還不知道已経關了。同時，為了真相能夠傳播，我肯定是能發就發，不會理你有沒有關。
